
environment:
  matrix:
    - PYTHON: "C:\\Python37"
      MINICONDA: "C:\\Miniconda37"
      PYTHON_VERSION: 3.7

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda
  - conda create -n test-env python=%PYTHON_VERSION% geopandas==0.6.1
  - activate test-env
  - python setup.py develop
  - python -m pip install -r %APPVEYOR_BUILD_FOLDER%\\requirements.txt -q

build: off

test_script:
  - pytest %APPVEYOR_BUILD_FOLDER%

  # Asserting pep8 formatting checks (using autopep8 tool)
  # - ps: |
  #     $output = %PYTHON%\\Scripts\\autopep8 -d --recursive .
  #     if($output)
  #     {
  #         echo $output;
  #         $host.SetShouldExit(1)
  #         Write-Host "autopep8 failed:
  #         Please this command locally:
  #         'autopep8 -i -a -r .'"
  #     }
